#!/bin/sh

mailLabel="ﯬ "

mail()
{
	[[ $(find ~/.mail/*/INBOX/new/*) ]] 2>/dev/null && newmail=$(find ~/.mail/*/INBOX/new/* | wc -l) || newmail=0
	[[ $newmail == 0 ]] || printf "\x03%s\x01 %s %s" "$mailLabel" "$newmail" "$SEP"
}
