#!/bin/sh

mailLabel=""

mail()
{
	[[ $(find ~/.mail/*/INBOX/new/*) ]] 2>/dev/null && newmail=$(find ~/.mail/*/INBOX/new/* | wc -l) || newmail=0
	[[ $newmail == 0 ]] || printf "%s %s %s" "$mailLabel" "$newmail" "$SEP"
}
