#!/bin/sh

wifi()
{
	wifi=""
	nmcli | grep 'connected' >/dev/null && netLabel="直" || netLabel="睊"
	[[ $netLabel="直" ]] && wifi=$(nmcli | awk '/connected/ {print $4}')
	printf "%s %s %s" "$netLabel" "$wifi" "$SEP"
}
